# Generated by Django 4.2.6 on 2023-10-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_cartitem_quantity_cart_items_cart_total_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
